server:
  port: 8080
  servlet.context-path: /${spring.application.name}/${spring.application.version}

grpc:
  server:
    port: 9090

---
spring:
  application:
    name: pagila-customer-svc
    version: v1
  profiles.active: ${SPRING_PROFILES_ACTIVE:postgres}
  banner.location: banner.txt
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create # none
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  sql.init.mode: never # always
  output.ansi.enabled: always

---
# Postgres properties
spring:
  config.activate.on-profile: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?currentSchema=public
      username: ${DB_USERNAME:srivatsan}
      password: ${DB_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: postgres-con

---
# Application Properties
global:
  debugModeEnabled: true